# Generated by Django 5.0 on 2024-01-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
