# Generated by Django 5.0 on 2024-01-17 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_posteo_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='posteo',
            field=models.ForeignKey(default=None , on_delete=django.db.models.deletion.CASCADE, to='mainApp.posteo'),
        ),
    ]
