# Generated by Django 5.0 on 2024-01-18 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_comentario_posteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='posteo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.posteo'),
        ),
    ]
